#!/bin/sh /etc/rc.common

START=95
STOP=10

start() {
    logger -t rxgro "Enabling rx-gro-list on interfaces..."

    for iface in br-lan wan lan1 lan2 lan3 lan4; do
        ethtool -K $iface rx-gro-list on 2>/dev/null
    done

    logger -t rxgro "rx-gro-list enabled."
}
